### PR TITLE
Pacemaker class

### PR DESCRIPTION
**Pull request by jlashner**
Adds a "Pacemaker" class to OCS to help Agents maintain regular sampling frequencies.

## Description

This PR adds a new helper class to OCS to help agents such as the Lakeshore372 maintain a regular sampling rate despite having data acquisition functions that take varying amounts of time. The Pacemaker also lets agents "quantize" their samples for sampling rates that are whole numbers, forcing samples to land on a temporal grid starting on the second, which will help synchronize data acquisition across agents. 

## Motivation and Context

Closes issue #152.

## How Has This Been Tested?

Added a test function that tests sampling regularity in a loop for  few seconds. Have not implemented into agents yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

### CODE REVIEW

**Review by mhasself — CHANGES_REQUESTED** [review]
This implementation uses time.sleep, and thus can't run in the twisted reactor.  Perhaps add a dsleep method that does the same thing but yields from dsleep?

**Review by BrianJKoopman — CHANGES_REQUESTED** [review]
## Tests
For completeness I think a couple more tests could be added. One that tests for invalid inputs when `quantize=True`, i.e.:
```
def test_non_integer_quantization():
    """Trying to quantize with a non-integer sampling frequency should raise an
    error.

    """
    with pytest.raises(ValueError):
        Pacemaker(5.5, quantize=True)
```
The other, which verifies the pacemaker works when `quantize=False`, the distinction maybe being that you include that first diff you omit in the current test due to the quantization.

**Comment by jlashner** [comment]
Implemented suggestions. I also tested the dsleep method with the following test:
```
from ocs.ocs_twisted import Pacemaker
from twisted.internet.defer import inlineCallbacks
from twisted.internet import reactor
import time

@inlineCallbacks
def test_dsleep():
    pm  = Pacemaker(3, quantize=True)
    for _ in range(10):
        yield pm.dsleep()
        print(time.time())

reactor.callWhenRunning(test_dsleep)
reactor.run()
```
However I'm not sure if we have the framework to test twisted functions with pytest yet.

**Review by BrianJKoopman — APPROVED** [review]
Looks good, thanks for the added tests.

On the topic of testing twisted functions. Twisted has their own test runner capable of this, called Trial, which is meant to stand in for the python `unittest` framework. However, there's also this `pytest-twisted` plugin, which might be worth checking out: https://pypi.org/project/pytest-twisted/

**Pull request merged**
