### PR TITLE
setup.py: add ocs.agent submodule

### PR DESCRIPTION
**Pull request by mhasself**

### CODE REVIEW

**Comment by mhasself** [comment]
Without this, the agent submodule is not installed and the aggregator Agent is not able to "import ocs.agent" unless running from the source tree.

**Comment by BrianJKoopman** [comment]
Can we import `find_packages` from setuptools and do a `packages = find_packages()`? That'll avoid forgetting to add a package in the future. socs does this.

**Comment by BrianJKoopman** [comment]
Cool, I dunno if I jumped the start on requesting review, but it seemed like a quick change. Approved!

**Comment by mhasself** [comment]
Closing to PR against develop branch.

**Pull request closed without merging**
