### PR TITLE
Deal gracefully with crossbar not being found

### PR DESCRIPTION
**Pull request by cnweaver**
Crossbar was not included in requirements.txt, which leads to some obscure errors from a fresh install on a clean system. 

## Description
This patch adds crossbar to requirements.txt so that users should generally not see this problem at all, and adds error checking to detect when crossbar cannot be found at runtime or the user has manually specified an invalid path to it. 

## Motivation and Context
This change prevents or renders more easy to understand problems with crossbar not being found. 

## How Has This Been Tested?
A new unit test is included to verify the behavior of these changes. 
Otherwise, the behavior can be verified by testing installation on any system which does not already have crossbar installed. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

### CODE REVIEW

**Comment by BrianJKoopman** [comment]
Hi Chris, thanks for the PR. Can you provide some more details on the obscure errors you ran into? If I had to guess, they're likely related to `ocsbow` trying to startup and interact with the `crossbar` server?

We used to have `crossbar` in our requirements file. Typically now the `crossbar` server will be left running in a Docker container on a system and not started/stopped by `ocsbow`. Back in Sept 2020 we were running into the `crossbar` package pinning dependencies that would then had further consequences (see #166 and #173), so we dropped it.

`crossbar` itself pulls in a ton of dependencies (as pointed out in #92). I, at one point, started to split out the various requirements to separate files for different purposes (i.e. if you only need to run an ocs client), but never really wrapped it up (that's the draft sitting in #167).

**Comment by cnweaver** [comment]
Indeed, the failure occurs when `ocsbow` tries to start `crossbar`, but the cause isn't very clear at first glance:
```$ make up
ocsbow --site-file default.yaml up
Trying to start crossbar...
Traceback (most recent call last):
  File "/home/cweaver/daq/bin/ocsbow", line 4, in <module>
    __import__('pkg_resources').run_script('ocs==0.8.0+8.gedccf36', 'ocsbow')
  File "/home/cweaver/daq/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cweaver/daq/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/cweaver/daq/lib/python3.8/site-packages/ocs-0.8.0+8.gedccf36-py3.8.egg/EGG-INFO/scripts/ocsbow", line 7, in <module>
    ocsbow.main()
  File "/home/cweaver/daq/lib/python3.8/site-packages/ocs-0.8.0+8.gedccf36-py3.8.egg/ocs/ocsbow.py", line 518, in main
    hm.crossbar_action('start')
  File "/home/cweaver/daq/lib/python3.8/site-packages/ocs-0.8.0+8.gedccf36-py3.8.egg/ocs/ocsbow.py", line 244, in crossbar_action
    pid = os.spawnv(flags, cmd[0], cmd)
  File "/usr/lib/python3.8/os.py", line 879, in spawnv
    return _spawnvef(mode, file, args, None, execv)
  File "/usr/lib/python3.8/os.py", line 846, in _spawnvef
    raise ValueError('argv first element cannot be empty')
ValueError: argv first element cannot be empty
make: *** [Makefile:15: up] Error 1
$ which crossbar || echo "not found" 1>&2
not found```

If you wanted to treat installation of crossbar separately I think that could be fine as long as it's made clear in the docs that the user needs to, as a deliberate step, follow one of the options to get it installed, and I think having this improved error message when the user misses that will help. Personally, I prefer just installing crossbar into the virtual environment in which I'm working, since Docker is a much heavier dependency, and often requires elevated privileges. 

If you prefer, I can remove the addition to `requirements.txt` from this PR, and instead update the docs to make it more clear that crossbar is _not_ installed with pip (as it is currently implied to be).

**Comment by BrianJKoopman** [comment]
> If you wanted to treat installation of crossbar separately I think that could be fine as long as it's made clear in the docs that the user needs to, as a deliberate step, follow one of the options to get it installed, and I think having this improved error message when the user misses that will help. Personally, I prefer just installing crossbar into the virtual environment in which I'm working, since Docker is a much heavier dependency, and often requires elevated privileges.

I agree that the improved error message would help.

> If you prefer, I can remove the addition to `requirements.txt` from this PR, and instead update the docs to make it more clear that crossbar is _not_ installed with pip (as it is currently implied to be).

That sounds good to me. Thanks!

**Comment by cnweaver** [comment]
This is now done.

**Review by BrianJKoopman — APPROVED** [review]
Looks good, thanks for the updates and the patch!

**Pull request merged**
